### ISSUE TITLE
Add Support for Windows

### ISSUE THREAD

**Issue by cmd-johnson** [cmd-johnson/node-power-info#7]
Currently, the module doesn't work on Windows, missing out on a large user-base.
Investigate where to get the battery information on Windows from and implement it.

**Comment by gigibiffi84** [comment]
os:Windows_NT function () {
  return process.arch;
} @ 10.0.10240

**Comment by hendrikbl** [comment]
There is a `Win32_Battery` class on Windows giving you access to battery info: https://msdn.microsoft.com/en-us/library/aa394074.aspx. Maybe this could be used for a Windows implementation?

**Comment by cmd-johnson** [comment]
SINce this package's main use probably is in [atom-battery-status](https://github.com/cmd-johnson/atom-battery-status), adding the Battery Status API provider (#10) finally makes it possible to use this on Windows.
The only restriction is that this requires the `navigator` object to exist, which it only does when runnig inside a browser, so this module still won't work on Windows in node.js.
